//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnDijon.Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DMResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnDijon.Common.Utils.Resources.DMResources", typeof(DMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://eservices.dijon.fr/Documents partages/App/mydijon_image_icon_commander_profile_active.
        /// </summary>
        public static string Child_Active_Icon {
            get {
                return ResourceManager.GetString("Child_Active_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://eservices.dijon.fr/Documents partages/App/mydijon_image_icon_commander_profile.
        /// </summary>
        public static string Child_Inactive_Icon {
            get {
                return ResourceManager.GetString("Child_Inactive_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://eservices.dijon.fr/Documents partages/App/.
        /// </summary>
        public static string Configuration_ImageSourceUriBase {
            get {
                return ResourceManager.GetString("Configuration_ImageSourceUriBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://pc170014.agglo-dijon.ad/_vti_bin/Apps/JonDiService.svc/json/AddFavori.
        /// </summary>
        public static string News_AddFavorite_Url {
            get {
                return ResourceManager.GetString("News_AddFavorite_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://pc170014.agglo-dijon.ad/_vti_bin/Apps/JonDiService.svc/json/GetArticle.
        /// </summary>
        public static string News_Article_Url {
            get {
                return ResourceManager.GetString("News_Article_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://pc170014.agglo-dijon.ad/_vti_bin/Apps/JonDiService.svc/json/GetAllCategorie.
        /// </summary>
        public static string News_Category_Url {
            get {
                return ResourceManager.GetString("News_Category_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://pc170014.agglo-dijon.ad/_vti_bin/Apps/JonDiService.svc/json/GetFavori.
        /// </summary>
        public static string News_Favorite_Url {
            get {
                return ResourceManager.GetString("News_Favorite_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://pc170014.agglo-dijon.ad/_vti_bin/Apps/JonDiService.svc/json/RemoveFavori.
        /// </summary>
        public static string News_RemoveFavorite_Url {
            get {
                return ResourceManager.GetString("News_RemoveFavorite_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_calendar_day.
        /// </summary>
        public static string SchoolRestaurantBooking_Calendar_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantBooking_Calendar_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévoir.
        /// </summary>
        public static string SchoolRestaurantBooking_Schedule_Action_Title {
            get {
                return ResourceManager.GetString("SchoolRestaurantBooking_Schedule_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulé.
        /// </summary>
        public static string SchoolRestaurantBooking_Status_Canceled_Title {
            get {
                return ResourceManager.GetString("SchoolRestaurantBooking_Status_Canceled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prévu.
        /// </summary>
        public static string SchoolRestaurantBooking_Status_Scheduled_Title {
            get {
                return ResourceManager.GetString("SchoolRestaurantBooking_Status_Scheduled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décommandé.
        /// </summary>
        public static string SchoolRestaurantBooking_Status_Unscheduled_Title {
            get {
                return ResourceManager.GetString("SchoolRestaurantBooking_Status_Unscheduled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_bio_active.
        /// </summary>
        public static string SchoolRestaurantCalendar_Bio_Active_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Bio_Active_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_bio.
        /// </summary>
        public static string SchoolRestaurantCalendar_Bio_Inactive_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Bio_Inactive_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_cheese.
        /// </summary>
        public static string SchoolRestaurantCalendar_Cheese_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Cheese_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_dessert.
        /// </summary>
        public static string SchoolRestaurantCalendar_Desert_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Desert_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_commerce_equitable_active.
        /// </summary>
        public static string SchoolRestaurantCalendar_FairTrade_Active_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_FairTrade_Active_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_commerce_equitable.
        /// </summary>
        public static string SchoolRestaurantCalendar_FairTrade_Inactive_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_FairTrade_Inactive_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_local_active.
        /// </summary>
        public static string SchoolRestaurantCalendar_Local_Active_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Local_Active_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_local.
        /// </summary>
        public static string SchoolRestaurantCalendar_Local_Inactive_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Local_Inactive_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_porc_active2.
        /// </summary>
        public static string SchoolRestaurantCalendar_Pork_Active_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Pork_Active_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_porc2.
        /// </summary>
        public static string SchoolRestaurantCalendar_Pork_Inactive_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Pork_Inactive_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_proteine.
        /// </summary>
        public static string SchoolRestaurantCalendar_Protein_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Protein_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_entree.
        /// </summary>
        public static string SchoolRestaurantCalendar_Starter_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Starter_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mydijon_image_icon_consulter_legume.
        /// </summary>
        public static string SchoolRestaurantCalendar_Vegetable_Icon {
            get {
                return ResourceManager.GetString("SchoolRestaurantCalendar_Vegetable_Icon", resourceCulture);
            }
        }
    }
}
